name: paradigm-ctf
services:
  database:
    container_name: database
    image: redis/redis-stack:latest
    ports:
      - '6379:6379'
      - '8001:8001'
    environment:
      - REDIS_ARGS=--save 60 1
    networks:
      - ctf_network
    volumes: 
      - database:/data
  ctf-server-orchestrator:
    container_name: orchestrator
    image: gcr.io/paradigmxyz/infra/paradigmctf.py:latest
    build: .
    user: root
    command: uvicorn ctf_server:orchestrator --host 0.0.0.0 --port 7283
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "7283:7283"
    environment:
      - BACKEND=docker
      - DATABASE=redis
      - REDIS_URL=redis://database:6379/0
    networks:
      - ctf_network
    depends_on:
      - database
  ctf-server-anvil-proxy:
    container_name: anvil-proxy
    image: gcr.io/paradigmxyz/infra/paradigmctf.py:latest
    build: .
    command: uvicorn ctf_server:anvil_proxy --host 0.0.0.0 --port 8545
    ports:
      - "8545:8545"
    environment:
      - DATABASE=redis
      - REDIS_URL=redis://database:6379/0
    networks:
      - ctf_network
    depends_on:
      - database
volumes:
  database:
    driver: local

networks:
  ctf_network:
    name: paradigmctf